files updated

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,7 +18,6 @@ jobs:
       ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      
 
     steps:
       # Checkout the repository
@@ -45,121 +44,109 @@ jobs:
       - name: Import Resource Group if not managed
         run: |
           terraform state show azurerm_resource_group.rg || \
-          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg
+          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg
         working-directory: terraform
 
       - name: Import Virtual Network if not managed
         run: |
           terraform state show azurerm_virtual_network.vnet || \
-          terraform import azurerm_virtual_network.vnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet
+          terraform import azurerm_virtual_network.vnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet
         working-directory: terraform
 
       - name: Import Subnet if not managed
         run: |
           terraform state show azurerm_subnet.subnet || \
-          terraform import azurerm_subnet.subnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet/subnets/tf-linux-vm-subnet
+          terraform import azurerm_subnet.subnet /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet/subnets/tf-linux-vm-subnet
         working-directory: terraform
 
       - name: Import Public IP if not managed
         run: |
           terraform state show azurerm_public_ip.public_ip || \
-          terraform import azurerm_public_ip.public_ip /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/publicIPAddresses/tf-linux-vm-public-ip
+          terraform import azurerm_public_ip.public_ip /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/publicIPAddresses/tf-linux-vm-public-ip
         working-directory: terraform
 
-      # - name: Import Network Interface if not managed
-      #   run: |
-      #     terraform state show azurerm_network_interface.nic || \
-      #     terraform import azurerm_network_interface.nic /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/networkInterfaces/tf-linux-vm-nic
-      #   working-directory: terraform
+      - name: Import Network Interface if not managed
+        run: |
+          terraform state show azurerm_network_interface.nic || \
+          terraform import azurerm_network_interface.nic /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/networkInterfaces/tf-linux-vm-nic
+        working-directory: terraform
 
-      # - name: Import Virtual Machine if not managed
-      #   run: |
-      #     terraform state show azurerm_linux_virtual_machine.linux_vm || \
-      #     terraform import azurerm_linux_virtual_machine.linux_vm /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Compute/virtualMachines/tf-linux-vm
-      #   working-directory: terraform
-      # - name: Import NSG if not managed
-      #   run: |
-      #     terraform state show azurerm_network_security_group.nsg || \
-      #     terraform import azurerm_network_security_group.nsg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/networkSecurityGroups/Network-NSG
-      #   working-directory: terraform
-      # # Import existing Network Security Group Association if not managed
-      # - name: Import Subnet NSG Association if not managed
-      #   run: |
-      #     terraform state show azurerm_subnet_network_security_group_association.nsg_association || \
-      #     terraform import azurerm_subnet_network_security_group_association.nsg_association /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet/subnets/tf-linux-vm-subnet
-      #   working-directory: terraform
+      - name: Import Virtual Machine if not managed
+        run: |
+          terraform state show azurerm_linux_virtual_machine.linux_vm || \
+          terraform import azurerm_linux_virtual_machine.linux_vm /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Compute/virtualMachines/tf-linux-vm
+        working-directory: terraform
+      - name: Import NSG if not managed
+        run: |
+          terraform state show azurerm_network_security_group.nsg || \
+          terraform import azurerm_network_security_group.nsg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/networkSecurityGroups/Network-NSG
+        working-directory: terraform
+      # Import existing Network Security Group Association if not managed
+      - name: Import Subnet NSG Association if not managed
+        run: |
+          terraform state show azurerm_subnet_network_security_group_association.nsg_association || \
+          terraform import azurerm_subnet_network_security_group_association.nsg_association /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/tf-linux-1-rg/providers/Microsoft.Network/virtualNetworks/tf-linux-vm-vnet/subnets/tf-linux-vm-subnet
+        working-directory: terraform
     
-      # # Terraform Plan
-      # - name: Terraform Plan
-      #   run: terraform plan -out=tfplan
-      #   working-directory: terraform
+      # Terraform Plan
+      - name: Terraform Plan
+        run: terraform plan -out=tfplan
+        working-directory: terraform
 
-      # # Terraform Apply
-      # - name: Terraform Apply
-      #   if: github.ref == 'refs/heads/main'
-      #   run: terraform apply -auto-approve tfplan
-      #   working-directory: terraform
+      # Terraform Apply
+      - name: Terraform Apply
+        if: github.ref == 'refs/heads/main'
+        run: terraform apply -auto-approve tfplan
+        working-directory: terraform
 
-      # # Retrieve Terraform Outputs
-      # - name: Retrieve Terraform Outputs
-      #   id: terraform_output
-      #   run: |
-      #     PUBLIC_IP=$(az network public-ip show \
-      #       --resource-group tf-linux-rg \
-      #       --name tf-linux-vm-public-ip \
-      #       --query ipAddress -o tsv)
-      #     echo "public_ip=${PUBLIC_IP}" >> $GITHUB_ENV  
-      #   working-directory: terraform
+      # Retrieve Terraform Outputs
+      - name: Retrieve Terraform Outputs
+        id: terraform_output
+        run: |
+          PUBLIC_IP=$(az network public-ip show \
+            --resource-group tf-linux-1-rg \
+            --name tf-linux-vm-public-ip \
+            --query ipAddress -o tsv)
+          echo "public_ip=${PUBLIC_IP}" >> $GITHUB_ENV  
+        working-directory: terraform
 
-      # #Decode the private key and save it to a file
-      # - name: Decode and save SSH private key
-      #   run: |
-      #     echo "${{ secrets.AZURE_PRIVATE_KEY }}" >> private_key.pem
-      #     chmod 600 private_key.pem
+      # Decode the private key and save it to a file
+      - name: Decode and save SSH private key
+        run: |
+          echo "${{ secrets.AZURE_PRIVATE_KEY }}" > private_key.pem
+          chmod 600 private_key.pem
 
-      #----------comment the above code after creation of VM
-
-      # # # Test SSH Connection (Add verbosity for troubleshooting)
-      # - name: Test SSH Connection
-      #   run: |
-      #     chmod 600 newprivatekeypair.pem
-      #     echo "Testing SSH connection to VM..."
-      #     pwd
-      #     ls -l 
-      #     ssh -i newprivatekeypair.pem -o StrictHostKeyChecking=no -vvv azureuser@40.85.153.118 echo "SSH connection successful"
-      #   shell: bash
+      # Test SSH Connection (Add verbosity for troubleshooting)
+      - name: Test SSH Connection
+        run: |
+          echo "Testing SSH connection to VM..."
+          ssh -i private_key.pem -o StrictHostKeyChecking=no -vvv azureuser@40.85.153.118 echo "SSH connection successful"
+        shell: bash
 
       # Install Ansible
-      # - name: Install Ansible
-      #   run: |
-      #     sudo apt-get install -y ansible
-      #     sudo python3 -m pip install --upgrade ansible
-      #     pip show ansible
-      #     sudo apt-get update
-      #     sudo apt-get install zlib1g
+      - name: Install Ansible
+        run: sudo apt-get install -y ansible
 
-      # Configure Ansible Inventory ------
-      # - name: Configure Ansible Inventory
-      #   run: |
-      #     echo "Configuring Ansible inventory file..."
-      #     echo "[azure_vm]" > inventory
-      #     echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
+      # Configure Ansible Inventory
+      - name: Configure Ansible Inventory
+        run: |
+          echo "Configuring Ansible inventory file..."
+          echo "[azure_vm]" > inventory
+          echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
           
-      #     if [[ ! -f "inventory" ]]; then
-      #       echo "Error: Ansible inventory file was not created."
-      #       exit 1
-      #     fi
+          if [[ ! -f "inventory" ]]; then
+            echo "Error: Ansible inventory file was not created."
+            exit 1
+          fi
 
-      #     echo "Ansible inventory file configured."
+          echo "Ansible inventory file configured."
 
       # Run Ansible Playbook
-      # - name: Run Ansible Playbook
-      #   run: |
-      #     chmod 600 newprivatekeypair.pem
-      #     python3 --version
-      #     echo "Running Ansible playbook..."
-      #     ansible-playbook -i inventory.ini setup.yml -u azureuser@40.85.153.118 --private-key=newprivatekeypair.pem --limit all -vvv
-      # ansible all -m command -a "echo hello" -i inventory.ini -vvv
+      - name: Run Ansible Playbook
+        run: |
+          echo "Running Ansible playbook..."
+          ansible-playbook -i inventory setup.yml
+
       # - name: Ensure Python 3 is Installed on VM
       # #   uses: docker://cytopia/ansible:latest
       # #   with:
@@ -189,5 +176,4 @@ jobs:
       #       apk add --no-cache sshpass &&
       #       ansible-playbook -i inventory ansible-playbook.yml
       #       "
-#git secret keys added
 
