commented

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -116,6 +116,8 @@ jobs:
           echo "${{ secrets.AZURE_PRIVATE_KEY }}" >> private_key.pem
           chmod 600 private_key.pem
 
+      #----------comment the above code after creation of VM
+
       # # # Test SSH Connection (Add verbosity for troubleshooting)
       # - name: Test SSH Connection
       #   run: |
@@ -135,19 +137,19 @@ jobs:
       #     sudo apt-get update
       #     sudo apt-get install zlib1g
 
-      # Configure Ansible Inventory
-      - name: Configure Ansible Inventory
-        run: |
-          echo "Configuring Ansible inventory file..."
-          echo "[azure_vm]" > inventory
-          echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
+      # Configure Ansible Inventory ------
+      # - name: Configure Ansible Inventory
+      #   run: |
+      #     echo "Configuring Ansible inventory file..."
+      #     echo "[azure_vm]" > inventory
+      #     echo "40.85.153.118 ansible_user=azureuser ansible_ssh_private_key_file=private_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
           
-          if [[ ! -f "inventory" ]]; then
-            echo "Error: Ansible inventory file was not created."
-            exit 1
-          fi
+      #     if [[ ! -f "inventory" ]]; then
+      #       echo "Error: Ansible inventory file was not created."
+      #       exit 1
+      #     fi
 
-          echo "Ansible inventory file configured."
+      #     echo "Ansible inventory file configured."
 
       # Run Ansible Playbook
       # - name: Run Ansible Playbook
